# Jonathon Repta
# CS 424 Project 3

# Load libraries
library(shiny)
library(shinydashboard)
library(ggplot2)
library(mapview)
library(tigris)
library(leaflet)

# Read in compressed data
energy <- read.csv(file = "data/Energy_Usage_2010_Cleaned.csv", sep = ",", header=TRUE)

ui <- fluidPage(
    title = "CS 424: Project 3",
    lang="en",
    p(),
    navbarPage("Project 3", position = c("static-top"), collapsible = FALSE, fluid = TRUE,
    tabPanel("Compare neighborhoods",
    fluidPage(
          column(6,
            fluidRow(column(6,
              selectInput(inputId="areaSelect1", width="100%", label="Neighborhood", choices=
              c("Albany Park",
              "Archer Heights",
              "Armour Square",
              "Ashburn",
              "Auburn Gresham",
              "Austin",
              "Avalon Park",
              "Avondale",
              "Belmont Cragin",
              "Beverly",
              "Bridgeport",
              "Brighton Park",
              "Burnside",
              "Calumet Heights",
              "Chatham",
              "Chicago Lawn",
              "Clearing",
              "Douglas",
              "Dunning",
              "East Garfield Park",
              "East Side",
              "Edgewater",
              "Edison Park",
              "Englewood",
              "Forest Glen",
              "Fuller Park",
              "Gage Park",
              "Garfield Ridge",
              "Grand Boulevard",
              "Greater Grand Crossing",
              "Hegewisch",
              "Hermosa",
              "Humboldt Park",
              "Hyde Park",
              "Irving Park",
              "Jefferson Park",
              "Kenwood",
              "Lakeview",
              "Lincoln Park",
              "Lincoln Square",
              "Logan Square",
              "Loop",
              "Lower West Side",
              "McKinley Park",
              "Montclare",
              "Morgan Park",
              "Mount Greenwood",
              "Near North Side",
              "Near South Side",
              "Near West Side",
              "New City",
              "North Center",
              "North Lawndale",
              "North Park",
              "Norwood Park",
              "O'Hare",
              "Oakland",
              "Portage Park",
              "Pullman",
              "Riverdale",
              "Rogers Park",
              "Roseland",
              "South Chicago",
              "South Deering",
              "South Lawndale",
              "South Shore",
              "Uptown",
              "Washington Heights",
              "Washington Park",
              "West Elsdon",
              "West Englewood",
              "West Garfield Park",
              "West Lawn",
              "West Pullman",
              "West Ridge",
              "West Town",
              "Woodlawn"),
              selected="Near West Side")),
              column(6,selectInput("monthSelect1", "Month", c("January" = "Jan","February" = "Feb","March" = "Mar","April" = "Apr","May" = "May","June" = "Jun","July" = "Jul","August" = "Aug","September" = "Sep","October" = "Oct","November" = "Nov","December" = "Dec"), selected="Jan", width="100%"))
            ),
            leafletOutput("testMap", height="calc(100vh - 245px)"),
            absolutePanel(top = 90, left=25, actionButton("resetButton1", "Reset Map")),
            checkboxGroupInput(inputId="checkboxGroup1",label="Energy Sources",inline=TRUE, width="100%", selected="all", choices =
              c("All" = "all",
                "Coal" = "coal",
                "Oil" = "oil",
                "Gas" = "gas",
                "Nuclear" = "nuclear",
                "Hydro" = "hydro",
                "Biomass" = "biomass",
                "Wind" = "wind",
                "Solar" = "solar",
                "Geothermal" = "geothermal",
                "Other" = "other",
                "Non renewable" = "non_renewable",
                "Renewable" = "renewable")
            )
          ),
          column(6,
            fluidRow(column(6,
              selectInput(inputId="areaSelect2", width="100%", label="Neighborhood", choices=
              c("Albany Park",
              "Archer Heights",
              "Armour Square",
              "Ashburn",
              "Auburn Gresham",
              "Austin",
              "Avalon Park",
              "Avondale",
              "Belmont Cragin",
              "Beverly",
              "Bridgeport",
              "Brighton Park",
              "Burnside",
              "Calumet Heights",
              "Chatham",
              "Chicago Lawn",
              "Clearing",
              "Douglas",
              "Dunning",
              "East Garfield Park",
              "East Side",
              "Edgewater",
              "Edison Park",
              "Englewood",
              "Forest Glen",
              "Fuller Park",
              "Gage Park",
              "Garfield Ridge",
              "Grand Boulevard",
              "Greater Grand Crossing",
              "Hegewisch",
              "Hermosa",
              "Humboldt Park",
              "Hyde Park",
              "Irving Park",
              "Jefferson Park",
              "Kenwood",
              "Lakeview",
              "Lincoln Park",
              "Lincoln Square",
              "Logan Square",
              "Loop",
              "Lower West Side",
              "McKinley Park",
              "Montclare",
              "Morgan Park",
              "Mount Greenwood",
              "Near North Side",
              "Near South Side",
              "Near West Side",
              "New City",
              "North Center",
              "North Lawndale",
              "North Park",
              "Norwood Park",
              "O'Hare",
              "Oakland",
              "Portage Park",
              "Pullman",
              "Riverdale",
              "Rogers Park",
              "Roseland",
              "South Chicago",
              "South Deering",
              "South Lawndale",
              "South Shore",
              "Uptown",
              "Washington Heights",
              "Washington Park",
              "West Elsdon",
              "West Englewood",
              "West Garfield Park",
              "West Lawn",
              "West Pullman",
              "West Ridge",
              "West Town",
              "Woodlawn"),
              selected="Loop")),
              column(6,selectInput("monthSelect2", "Month", c("January" = "Jan","February" = "Feb","March" = "Mar","April" = "Apr","May" = "May","June" = "Jun","July" = "Jul","August" = "Aug","September" = "Sep","October" = "Oct","November" = "Nov","December" = "Dec"), selected="Jan", width="100%"))
            ),
            leafletOutput("testMap2", height="calc(100vh - 245px)"),
            absolutePanel(top = 90, left=25, actionButton("resetButton2", "Reset Map")),
            checkboxGroupInput(inputId="checkboxGroup2",label="Energy Sources",inline=TRUE, width="100%", selected="all", choices =
              c("All" = "all",
                "Coal" = "coal",
                "Oil" = "oil",
                "Gas" = "gas",
                "Nuclear" = "nuclear",
                "Hydro" = "hydro",
                "Biomass" = "biomass",
                "Wind" = "wind",
                "Solar" = "solar",
                "Geothermal" = "geothermal",
                "Other" = "other",
                "Non renewable" = "non_renewable",
                "Renewable" = "renewable")
            )
          )
        )
    ),
  tabPanel("About",
    verbatimTextOutput("name"),
    verbatimTextOutput("date"),
    verbatimTextOutput("dataset")
  )
))

server <- function(input, output, session) {
  # About page
  output$name <- renderPrint({
    "Created by: Jonathon Repta"
  })
  output$date <- renderPrint({
    "Created on: April 24, 2021"
  })
  output$dataset <- renderPrint({
    "Data from: https://data.cityofchicago.org/Environment-Sustainable-Development/Energy-Usage-2010/8yq3-m6wp, Energy Usage 2010"
  })
}

shinyApp(ui, server)
